name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 4.1.1
      - name: Configure CMake
        if: ${{ matrix.os != 'windows-latest' }}
        run: cmake -B build
      - name: Configure CMake (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: cmake -B build -G "Visual Studio 17 2022" -A x64
      - name: Build
        run: cmake --build build

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 4.1.1
      - name: Configure CMake
        if: ${{ matrix.os != 'windows-latest' }}
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      - name: Configure CMake (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: cmake -B build -G "Visual Studio 17 2022" -A x64
      - name: Build
        run: cmake --build build --config Release
      - name: Run Tests
        run: build/Tests
        if: ${{ matrix.os != 'windows-latest' }}
      - name: Run Tests (Windows)
        run: ./build/Release/Tests.exe
        if: ${{ matrix.os == 'windows-latest' }}
