name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 4.1.1
      - name: Configure CMake
        run: cmake -B build
      - name: Build
        run: cmake --build build

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 4.1.1
      - name: Configure CMake
        run: cmake -B build
      - name: Build
        run: cmake --build build
      - name: Run Tests
        run: build/Tests
        if: ${{ matrix.os != 'windows-latest' }}
      - name: Run Tests (Windows)
        run: build\Tests.exe
        if: ${{ matrix.os == 'windows-latest' }}
